### ISSUE TITLE
[#2] Criar modelo para prever sintomas da depressão através de tweets

### ISSUE THREAD

**Issue by andrewlucasgs** [deeplearningunb/Iris#5]
O que fazer:
- [x] Pesquisar qual rede neural melhor para esse problema
- [x] Desenvolver algoritmo da rede neural
- [x] Treinar rede 
- [x] Testar rede

**Comment by mansogf** [comment]
O modelo passou por todos os modelos de aceitação e foi finalizado com sucesso! 

![](https://media.giphy.com/media/9xg1GNEiYfYrFMS5Kj/giphy.gif)
