### ISSUE TITLE
[#3] Coletar tweets dos usuários dignosticados com depressão

### ISSUE THREAD

**Issue by andrewlucasgs** [deeplearningunb/Iris#7]
Os usuários forma divididos em 45 arquivos csv, para melhor divisão do trabalho.

Passos:
1- Abra o notebook scraping_tweets_by_user
2- altere o nome do csv que sera lido de acordo com o numero escolhido
3- execute as celulas
4- commit o que foi coletado e armazenado na pasta users

Marque os que vc irá coletar nessa lista:
- [x] 0
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [x] 12
- [x] 13
- [x] 14
- [x] 15
- [x] 16
- [x] 17
- [x] 18
- [x] 19
- [x] 20
- [x] 21
- [x] 22
- [x] 23
- [x] 24
- [x] 25
- [x] 26
- [x] 27
- [x] 28
- [x] 29
- [x] 30
- [x] 31
- [x] 32
- [x] 33
- [x] 34
- [x] 35
- [x] 36
- [x] 37
- [x] 38
- [x] 39
- [x] 40
- [x] 41
- [x] 42
- [x] 43
- [x] 44
- [x] 45

**Comment by zarbielli** [comment]
Foi feito o scrapping em todos os arquivos!
