### ISSUE TITLE
[#4] Identificar stop words no dataset

### ISSUE THREAD

**Issue by zarbielli** [deeplearningunb/Iris#8]
Levando em consideração a metodologia abordada no artigo, identificar stop words.
https://aclweb.org/anthology/W18-0609

Use o seguinte código para identificar as palavras além das apontadas pelo artigo:

    counter = Counter()
    for tweet in tweets.tweet:
        splitted_tweet = re.split(r'\W', tweet)
        frequencias = Counter(splitted_tweet)
        counter.update(frequencias)
    for word in stopwords:
        del counter[word]
    counter.most_common(50)

O código pode ser visto tambem em: https://github.com/deeplearningunb/Iris/blob/devel/scraping_tweets_by_search.ipynb

**Comment by mansogf** [comment]
Done! 

![](https://media.giphy.com/media/Y3FvDlbT53Om7xwAPk/giphy.gif)
