### ISSUE TITLE
[#5] Remover stop words to dataset

### ISSUE THREAD

**Issue by zarbielli** [deeplearningunb/Iris#9]
Remover as palavras identificadas na #8, leve em consideração o artigo e retire URL's, caracteres não alfa-numéricos, pronomes ( menos Eu ) e preposições.

- [x] URL's.
- [x] Caracteres não alfa-numéricos.
- [x] Pronomes.
- [x] Preposições. 

Artigo: https://aclweb.org/anthology/W18-0609

**Comment by andrewlucasgs** [comment]
Feito
